### ISSUE TITLE
Visual Studio 2010 support

### ISSUE THREAD

**Issue by sandrock** [whatupdave/hamleditor#3]
Hi,
Is this supposed to work with VS 2010? It seems not.
Is there any plan to implement the same feature for VS 2010? This would be appreciated.
Thank you :)

**Comment by whatupdave** [comment]
Hi, this project is really old! Check out http://github.com/NHaml/NHamlVisualStudio

**Comment by sandrock** [comment]
Oh... Indeed.
Thank you anyway :)

**Comment by sandrock** [comment]
http://code.google.com/p/nhaml/wiki/VisualStudioPlugin
You project is still the official integration addin on the wiki.
